---
title: Flow Chart
---

flowchart TD
    ShowMainMenu[[Show Main Menu]]
    ClickPlay{Click Play?}


    ShowCharacterSelect[[ShowCharacterSelect]]
    SelectedCharacter{Selected Character?}
    PlayGame[[Play Game]]
    IsPlayerAlive?{Is Player Alive?}

    Start --> ShowMainMenu
    ShowMainMenu --> ClickPlay
    ClickPlay -- Yes --> ShowCharacterSelect

    ShowCharacterSelect --> SelectedCharacter
    SelectedCharacter -- Yes --> PlayGame

    PlayGame --> IsPlayerAlive? -- Yes --> PlayGame
    IsPlayerAlive? -- No --> Stop